model_training:
  Available_CPU: 24
  CPU_MULTI_THREADING: false
  HYBRID_MODE: false
  TF_GPU_ALLOCATOR: false
  autoencoder_architecture:
  - 1200
  - 800
  - 400
  - 200
  batchsize: 4
  enable_memory_growth: false
  l1_regularization: 0.0001
  l2_regularization: 0.0001
  label_latent_size: 200
  learning_rate: 1e-4
  loss_function: masked_mse
  metric_accuracy: SparseCategoricalAccuracy
  min_delta: 0.001
  mixed_precision: false
  model_file_extension: weights.h5
  model_name: testModel
  n_epochs: 500
  one_hot_encoding: false
  output_activation: sigmoid
  patience: 20
  regularization: l2
  seed: 101
  use_gradient_tape: false
