architecture:
- 1200
- 800
- 400
- 200
batchsize: 4
decoder_names:
- decoder_layer1
- decoder_layer2
- decoder_layer3
encoder_names:
- encoder_layer1
- encoder_layer2
- encoder_layer3
epochs: 500
fig_path: out/R0_Triplet_Data_Flex_F1_pink_prune_2pool_rgb/R0_Triplet_Data_Flex_F1_F_Pink_bg/model
input_dim: 358722
l1_regularization: 0.0001
l2_regularization: 0.0001
label_latent_size: 200
learning_rate: 0.0001
log_date: '2025-06-17'
loss_function: masked_mse
modelName: testModel
model_path: out/R0_Triplet_Data_Flex_F1_pink_prune_2pool_rgb/R0_Triplet_Data_Flex_F1_F_Pink_bg/model
one_hot_encoding: false
output_activation: sigmoid
patience: 20
regularization: l2
timestamp: 12-58-51
total_training_time: '0:51:42.017769'
use_gradient_tape: false
