name: Docker Login and Publish

on: [push]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - uses: actions/checkout@v2
      - name: Build the image
        run: | 
          docker build --tag ghcr.io/osu-hep-hdl/pixal-lite:latest .
      - name: Push the image
        run: docker push ghcr.io/osu-hep-hdl/pixal-lite:latest